Fix #5: add translations
llaski/nova-scheduled-jobs pull request #16
Opened 2019-09-09 13:38 UTC by klimov-paul

Fixes #5: add translations

2019-09-12 17:21 UTC, llaski commented
@klimov-paul Thanks for the PR - will try to review this tonight.

2019-09-26 01:31 UTC, llaski requested changes
@klimov-paul The general setup looks good, but it's missing the publishing and loading of the language files via the service provider.

Please add the following to the NovaScheduledJobsServiceProvider.php file:

In the boot method:

```
$this->publishes([
            __DIR__.'/../resources/lang/' => resource_path('lang/vendor/nova-scheduled-jobs'),
        ]);

        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'nova-scheduled-jobs');

        $this->registerTranslations();
```

Add this method as well:

```
protected function registerTranslations()
    {
        $currentLocale = app()->getLocale();

        Nova::translations(__DIR__.'/../resources/lang/'.$currentLocale.'.json');
        Nova::translations(resource_path('lang/vendor/nova-scheduled-jobs/'.$currentLocale.'.json'));

        $this->loadTranslationsFrom(__DIR__.'/../resources/lang', 'NovaScheduledJobs');
        $this->loadJSONTranslationsFrom(__DIR__.'/../resources/lang');
        $this->loadJSONTranslationsFrom(resource_path('lang/vendor/nova-scheduled-jobs'));
    }
```

2019-09-30 11:55 UTC, klimov-paul commented
Service provider adjusted

2019-09-30 13:17 UTC, llaski approved these changes

2019-09-30 13:17 UTC, merged